### ISSUE TITLE
Publish SDK 1.4.1

### ISSUE THREAD

**Issue by wes-b** [microsoft/Azure-Kinect-Sensor-SDK#1206]
**MSI Link:** [[1.4.1](https://download.microsoft.com/download/3/d/6/3d6d9e99-a251-4cf3-8c6a-8e108e960b4b/Azure%20Kinect%20SDK%201.4.1.exe)]
**Nuget Link:** [[1.4.1](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.1)]
**Deb package link:** [[AMD64](http://packages.microsoft.com/ubuntu/18.04/prod/pool/main/libk/)] [[ARM64](http://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/libk/)]
**Firmware:** [[1.6.110079014](https://download.microsoft.com/download/3/d/6/3d6d9e99-a251-4cf3-8c6a-8e108e960b4b/AzureKinectDK_Fw_1.6.110079014.bin)]
Summary of changes [are here](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/release/1.4.x/CHANGELOG.md)

**Comment by Kristian-Gregersen-KRGR** [comment]
Hi!
When do you expect to release the Debian package? Is “soon” this week, next week or...? 
Thanks!

**Comment by UnaNancyOwen** [comment]
@wes-b Azure Kinect Sensor SDK v1.4.1 seems has been published at [NuGet Gallery](https://www.nuget.org/packages/Microsoft.Azure.Kinect.Sensor/1.4.1) and [APT Package Repository](https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/libk/libk4a1.4/). At the least, that NuGet package does not appear to be a beta version, because package name without -beta.x and -alpha.x. However, Azure Kinect Sensor SDK v1.4.1 is not tagged at [GitHub](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/releases).  What’s happening?

**Comment by wes-b** [comment]
Thank you for pointing this out. There was a failure in our automation. We will get the MSI and other updates out shortly.

**Comment by UnaNancyOwen** [comment]
@wes-b Thanks, Please also update download link in Microsoft Docs. :)
https://docs.microsoft.com/en-us/azure/kinect-dk/sensor-sdk-download#windows-download-link

**Comment by chethanab16** [comment]
Hi, 
1. Is Azure-Kinect-Sensor-SDK supported on Lattepanda (Windows OS) ,  Raspberry Pi 4 (Windows ARM OS) and Intel Compute Stick ? 
2. Does Microsoft hololense  azure kinect  is same as new azure kinect camera?
thank you in advance.
