### ISSUE TITLE
Depth camera bit precision

### ISSUE THREAD

**Issue by johnvanatta** [microsoft/Azure-Kinect-Sensor-SDK#1331]
Documentation questions:
I see from the [documentation](https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___enumerations_gabd9688eb20d5cb878fd22d36de882ddb.html#gabd9688eb20d5cb878fd22d36de882ddb)
that depth values are 16 bit integers, units in mm. 

From the [hardware specs](https://docs.microsoft.com/en-us/azure/kinect-dk/hardware-specification) operating ranges vary based on the depth camera mode.

1. What's the depth bit precision? Is it linear throughout the range, or do closer values have higher precision? Is it the same or different for the different camera modes?
2. The footnote on the hardware specs page notes that values may be possible outside the range. Which means the maximum and minimum bit values are presumably outside the stated range? Is zero the minimum possible depth reading?
3. Is it possible to adjust the precision? I'm working on a close range robotics application, and would be happy to trade away maximum range in exchange for greater precision up close.

Thanks!

**Comment by qm13** [comment]
1.	The temporal standard deviation of the range measurements is not constant over range. It is a function of 

- Distance (closer is better, up until sensor saturation)
- Reflectivity (higher is better)
- Angle of incidence (lower angle is better)
- Location in the FOV
- Ambient light levels (lower spectral content ~850 nm is better)
- Field of illumination (narrower is better)

2.	Yes. It is impossible to get a depth reading corresponding to the maximum value of the 16 bit integer. For most applications the minimum distance is limited by saturation and the given specs are merely a guide to minimum performance parameters, not the actual device performance (see the above list).
3.	The ability to freely change the precision and/or dynamic range of the system is not exposed to the user, because it completely invalidates the calibration parameters. The only available precision trade-offs are by changing between the different binning and narrow/wide configurations. The wide configuration will have worse temporal standard deviation, but will be able to range closer to a given high reflectivity object with valid depth. Binning should have only limited impact on minimum imaging distance.

**Comment by johnvanatta** [comment]
Thank you
