### ISSUE TITLE
Depth errors when measuring human skin

### ISSUE THREAD

**Issue by crux24** [microsoft/Azure-Kinect-Sensor-SDK#1341]
**Background:**
We are trying to measure the height of hands and feet from a top-bottom setup of an Azure Kinect. 

**Problem:** 
When calculating the distance of depth between the highest point of the extremity and the ground, which represents the height, we constantly measure a discrepancy to reality. Specifically around 8-15mm less than the ground truth.

**Measurements:**
We tried measuring from different heights, different Kinect cameras, angles, and objects, and our first guess leads to "material" issue. When putting on socks or measuring boxes, the height seems to be correct. 

**Experiment:** 
So for a quick evaluation we took depth and rgb images from a hand/box, and afterwards from the same object with a piece of paper taped above them. See  clipped images below:
![tape_on_hand_dark_color_2](https://user-images.githubusercontent.com/50954543/92012838-45f26680-ed4d-11ea-9a72-7e904dc00419.png)
![tape_on_hand_dark_color_1](https://user-images.githubusercontent.com/50954543/92012862-4c80de00-ed4d-11ea-8806-1b6813b83a28.png)
![tmp_color_2](https://user-images.githubusercontent.com/50954543/92012941-66222580-ed4d-11ea-8e3f-9a70fec26393.png)
![tmp_color_1](https://user-images.githubusercontent.com/50954543/92012950-68847f80-ed4d-11ea-9228-fc7430ca11d2.png)

**Expectation:**
When calculating the difference of the images with and without paper attached we would expect only small variations between the images.

**Results:**
The first image is the difference image of the box. As you can see there are small differences in the area where the paper was placed, but they are in the range of 1 mm.
![tmp_diff_red_circle](https://user-images.githubusercontent.com/50954543/92013728-74bd0c80-ed4e-11ea-83bf-bf256ee1d498.png)
Whereas when looking at the hand image, differences in the range of 8mm are visible.
![tape_on_hand_dark_diff_red_circle](https://user-images.githubusercontent.com/50954543/92014208-265c3d80-ed4f-11ea-94e5-becd5d23620e.png)

**Explaination?**
 Is the human skin as reflection "material" unsuitable, so that measurements of plain skin may always lead to errors in this range, or are we missing something else here?
And if it's really the skin, are there ways to correct these errors?

Thanks in Advance!

**Comment by jasjuang** [comment]
I agree material severely affects the depth accuracy. I've reported my findings last year here https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/803#issuecomment-570006001.

**Comment by qm13** [comment]
Some materials such as human skin and certain plastics (e.g. red LEGO blocks) are fully or partially transmissive of near-IR wavelengths. When the active illumination from the depth sensor reaches the object, rather than being wholly reflected at the air-object interface it penetrates and is scattered, resulting in the mean path length travelled by the illumination being longer than expected (and thus the estimated range being farther away than is actually the case). This can be considered to be a type of multipath interference. There is no trivial way to detect this behavior in the most general case, given the small path length differences involved. This problem is not specific to the Kinect for Azure depth sensor and is a general problem for ToF depth imaging in the near-IR. 

For most applications this offset is not an issue, however if it is problematic and better accuracy is desired there are many possible heuristic solutions. For example, if you are designing for a use case where you start with the specific knowledge that you are going to be tracking a human hand, then you may wish to apply a correction factor to the hand based upon that knowledge.

**Comment by crux24** [comment]
@jasjuang, yes thank you, we've read the thread. It actually was the reason, why we ended up searching in this direction.
@qm13 thank you too for your explanation! Sadly the age or skin color of our probands may vary, so that a fixed correction factor may not be enough. But we are currently looking into other workarounds, so thanks again.
