### ISSUE TITLE
C# support

### ISSUE THREAD

**Issue by joylital** [microsoft/Azure-Kinect-Sensor-SDK#136]
- [x] .NET Standard wrapper
- [x] Functional tests
- [x] Unit tests
- [X] CI Automation
- [X] NuGet Packaging
- [X] SDK Packaging

# C# support

**Target .NET Frameworks**
- .NET Framework (desktop apps)
- .NET Core (Windows and Linux)

**Target UI Framewoks**
- WPF
- WinForms

**Comment by vpenades** [comment]
@Brent-A I have some thoughts for the C# wrapper:

I've noticed the body tracking SDK uses some structures of the Kinect4A DK, in particular it uses `k4a_result_t`, `k4a_calibration_t`, `k4a_wait_result_t`, `k4a_capture_t` , and might use others too...

I don't know if it's possible, but it could be interesting if the new Body tracker could be used offline, even without a device plugged, for which it could be interesting to use the body tracker without dragging the whole Microsoft.Azure.Kinect.Sensor....  so I was thinking if it could be possible to split the project into two assemblies.... something that would only containt the core, exchangeable types (so it could be used separately) and another one for the actual API.

About accessing IntPtr* .... its something we do use in our current implementation of Kinect2 for performance reasons, if such an API is considered, it could be nice if the exposed API uses ReadOnlySpan<T> instead of IntPtr*

**Comment by MsDerekMa** [comment]
The bulk of the C# support is in develop now and we are mostly working on cleanup, bugs, and documentation. Closing this issue out in favor of individual issues for the remaining work.

**Comment by Sn34k** [comment]
By Chance is this SDK for the V2 Kinect Sensor!?

**Comment by MsDerekMa** [comment]
This SDK only supports the [Azure Kinect DK](https://azure.microsoft.com/en-us/services/kinect-dk/). It does not support the Kinect for Windows v2.

**Comment by hcghanta** [comment]
When can I expect the C# wrapper for Body Tracking SDK?

**Comment by ispysoftware** [comment]
~tumbleweed~

**Comment by dhgokul** [comment]
@MsDerekMa  Any updates on C# wrapper for Body Tracking ?

**Comment by dhgokul** [comment]
Guys check it below link,it may be useful
https://ivatilca.wordpress.com/2019/08/22/first-azure-kinect-app-c-api-vs-c-k4a-nuget-package/  - Explain both how to use C API and C# API

**Comment by MsDerekMa** [comment]
@dhgokul as noted in #689, we don't have the the C# wrapper for Body Tracking planned. We are tracking the request on the feedback site, https://feedback.azure.com/forums/920053-azure-kinect-dk/suggestions/38661742-bodytracking-c-wrapper, to help us understand interest levels.
