### ISSUE TITLE
Missing points in pointcloud

### ISSUE THREAD

**Issue by DirkKramer** [microsoft/Azure-Kinect-Sensor-SDK#1449]
We believe we are missing some points in the pointcloud data, see below pictures from the azure kinect viewer and our viewer.

![azure_kinect_viewer](https://user-images.githubusercontent.com/46933603/102763250-b31c1d00-4379-11eb-9152-0d07a530588b.PNG)
![Rapid_viewer](https://user-images.githubusercontent.com/46933603/102763255-b4e5e080-4379-11eb-99b8-aeb7bff19785.PNG)

Configuration is s as follows
-Windows 10 
-SDK version 1.4.1
-C#
-NVOF Unbinned
-BG

```

(code to get points)
using (var depthimage = Transformation.DepthImageToPointCloud(cap.Depth))
                            {
                               
                                Short3[] xyzArray = depthimage.GetPixels<Short3>().ToArray();
                                for (int i = 0; i < xyzArray.Length; i++)
                                {
                                    positions.Add(new Vector3(xyzArray[i].X, xyzArray[i].Y, xyzArray[i].Z - (TanX * (xyzArray[i].Y - DegreeOffset))));
                                    colors.Add(new Color4(colorPixels[i].R / 255f, colorPixels[i].G / 255f, colorPixels[i].B / 255f, colorPixels[i].A / 255f));
                                }
                            }
```

Is it possible we can get the missing points data, if yes: how?

**Comment by diablodale** [comment]
What is the value of the depthmap at those points? If the depth pixels are invalid or 0, then you will have no voxels (pointcloud) data for that point. It is very common for depth data to be unavailable due to dust particles. Perhaps there is a dust particle in this area that is blocking the laser or its reflection. Or dirt or dust is at that specific location on the Kinect plastic cover or lens.
