### ISSUE TITLE
one PC, 4 kinect  sensor,  The maximum number of body tracking supported?

### ISSUE THREAD

**Issue by seoyeo** [microsoft/Azure-Kinect-Sensor-SDK#1489]
I have 4 kinect sensor, use body tracking in Unity, now i can tracking 6 body . But I want to be able to tracking 15-20 body, what should i do? thanks!

**Comment by L4Z3RC47** [comment]
You can run each Kinect sensor on separate networked computers and use multiplayer HLAPI to handle merging all of the tracked skeletons. Note that you would then need to ensure that each cameras covered area does not overlap otherwise you may get duplicated skeletons. Additionally each camera zone will still only be able to track up to 6 skeletons. This is probably the simplest way to increase tracked bodies

**Comment by seoyeo** [comment]
thanks for your reply！
Are there other ways to increase body tracking count？I mean break 6 body tracking limits use a kinect sensor.
