### ISSUE TITLE
k4abt_simple_3d_viewer failure ( Shader error : imageLoad  - undeclared identifier)

### ISSUE THREAD

**Issue by caohena** [microsoft/Azure-Kinect-Sensor-SDK#1492]
![E102Y 4`TN@~J10$_Y8X}CT](https://user-images.githubusercontent.com/28190881/105795953-b3d34f00-5fc8-11eb-85cd-de5168a32e7e.png)

I can use the k4aviewer.exe to show the color and depth frame
 but when i open the k4abt_simple_3d_viewer.exe to use the body tracking sdk, it shows the mistake like above, what should I do to solve the problem
My environment is : win10, Azure Kinect SDK v1.4.1，and I have  installed the OpenGL .
My graphics card is HD graphics 4000, so I use the CPU method to run this, Is this the reason?

**Comment by vladalx** [comment]
The reason you're getting this is because "imageLoad" is a GLSL function available since version 4.2 of OpenGL:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/imageLoad.xhtml

HD Graphics 4000 only supports OpenGL up to version 4.0 on Windows :
https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Seventh_generation
![image](https://user-images.githubusercontent.com/72383531/105862008-ff512180-5ff7-11eb-813a-5a5427c0bd18.png)
