### ISSUE TITLE
depth to color transformation creates unnecessarily large artefacts

### ISSUE THREAD

**Issue by fractalfantasy** [microsoft/Azure-Kinect-Sensor-SDK#1495]
The **k4a_transformation_depth_image_to_color_camera()** transformation in the sensor SDK makes the black "invalid" pixels (or as I like to call them "depth shadows") much larger than they should be. I tried the same transformation in Photoshop, and the "invalid" pixels were much less prominent. 

These artefacts can be quite ugly and hard to manage, especially in art applications. I think the code may just require a bit of tweaking.

I made a picture to showcase the **expected** vs **current** transformations results. Please excuse the blurryness... I used a small picture from the [k4a documentation](https://docs.microsoft.com/en-us/azure/kinect-dk/use-image-transformation).

![depth_to_color comparison expected](https://user-images.githubusercontent.com/12879320/106172535-eb74ff00-6160-11eb-9de1-7a602bcfe42b.jpg)

**Comment by SirLynix** [comment]
What transformation did you apply in Photoshop, did you just "undistort" the image? If so, this is incorrect.

k4a_transformation_depth_image_to_color_camera applies a transformation from the depth sensor to the rgb sensor, which is why there's so much black area : those are the pixels without depth information.

![](https://camo.githubusercontent.com/cfa61b8bce440812da346d50c7034875d017a98c5eb251b36f85a59e4fc566e2/68747470733a2f2f696d616765732e6374666173736574732e6e65742f7266367239776834626e72682f31697134376f34714f326355696f5336656b734959612f35356439333735373238633239356239343462626561653239393866323263352f53696e676c652d4f63636c7573696f6e536861646f77732d76322e706e67)

**Comment by fractalfantasy** [comment]
@SirLynix sorry just realize I left this unanswered... yes I removed the barrel distortion using a distort filter in photoshop (didn't do anything additional. Was trying to understand what was going on.

Your answer makes sense, depth_to_color transformation isn't just distortion correction but the depth pixels need to be re-aligned to the rgb image. And this process creates even more gaping holes of invalid pixels. 

--

Not sure if this is of importance to you guys:

The depth holes are much more prominent with Azure Kinect than with Kinect v1 and v2... There are 100s of papers on how to correct these holes, but they are quite hard to apply to Azure Kinect data that often has > 30% invalid pixels (not just a little bit along the edges).

We have a small team of developers trying to figure out this issue but it's a toughy... see the attached pictures from our dev thread (invalid pixels are red)
![holes2](https://user-images.githubusercontent.com/12879320/116740312-db202a80-a9c2-11eb-97d2-2b52a3d538f0.jpg)
![holes 3](https://user-images.githubusercontent.com/12879320/116740314-dbb8c100-a9c2-11eb-9d18-1ed43b9466c2.jpg)
![holes](https://user-images.githubusercontent.com/12879320/116740310-da879400-a9c2-11eb-9c61-46072586b37f.png)
