### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by H-Park** [microsoft/Azure-Kinect-Sensor-SDK#1627]
Is the SDK thread safe? If two threads call a method on a device at the same, what will happen? Is it recommended to use a mutex?

**Comment by diablodale** [comment]
in general, the SDK is intended to be thread safe. Sometimes bugs are found and fixed like https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/676

I have a multithreaded app with up to 16 threads all calling various K4A apis simultaneously. Naturally, I use the c++ api so that reference counting across threads, construction/destruction are handled automatically.

**Comment by H-Park** [comment]
That's great! Can a developer of the SDK verify that it is indeed thread safe?

**Comment by qm13** [comment]
It is designed to be thread safe.
