### ISSUE TITLE
HD 620 on Surface Laptop produces incorrect transformation results

### ISSUE THREAD

**Issue by cdedmonds** [microsoft/Azure-Kinect-Sensor-SDK#294]

**Comment by rabbitdaxi** [comment]
The issue seems very specific related to the intel older version driver, but somehow the surface laptop or surface book does not update the graphics driver automatically to the latest with windows update. The symptom of the issue is the color point cloud will see "missing points" and visually looks bad. Some workaround:
1) If you running surface book, instead of using the integrated intel graphics, you can switch to the NVidia graphics which should running perfect
2) If you have to use the HD620 or HD520 integrated graphics, you need to update the driver to the latest. If you are having issue to install driver on surface, one way is you need to download the zip file and extract the zip. Then you can go to device manager, right click the intel graphics under display adaptor, then follow the UI to install from local folder (use the path that you extracted from the zip). After you successfully update the driver to latest (e.g. from a old version that windows update had for surface book/laptop: 24.20.100.6293 to the new version that currently available 26.20.100.6709), issue will be resolved

**Comment by cdedmonds** [comment]
Resolving this since it is fixed by updated drivers.
