### ISSUE TITLE
Document how to avoid depth camera interference when using multiple camera's

### ISSUE THREAD

**Issue by wes-b** [microsoft/Azure-Kinect-Sensor-SDK#436]
**Describe the bug**
When using multiple depth camera's in synchronized captures, depth camera captures should be offset from one another by 160us or more.

**Comment by tesych** [comment]
it is documented as part of the [Hardware specification](https://docs.microsoft.com/en-us/azure/Kinect-dk/hardware-specification#external-synchronization)

**Comment by iammarvelous** [comment]
Hi, I was going through documents about multiple devices sync. I finally ended up here because I was wondering how to set sync-delay. I think [this document](https://docs.microsoft.com/en-us/azure/Kinect-dk/record-external-synchronized-units) should also be updated to avoid confusion. To be clear, I want to check with you that the following is the correct way to do multiple devices sync:
```
# for master
k4arecorder.exe --device 0 --external-sync master output-1.mkv
# for subordinate-1
k4arecorder.exe --device 1 --external-sync subordinate --sync-delay 0.16 output-2.mkv
# for subordinate-2
k4arecorder.exe --device 2 --external-sync subordinate --sync-delay 0.32 output-3.mkv
```

**Comment by wes-b** [comment]
> Hi, I was going through documents about multiple devices sync. I finally ended up here because I was wondering how to set sync-delay. I think this document should also be updated to avoid confusion. To be clear, I want to check with you that the following is the correct way to do multiple devices sync:
> # for master
> k4arecorder.exe --device 0 --external-sync master output-1.mkv
> # for subordinate-1
> k4arecorder.exe --device 1 --external-sync subordinate --sync-delay 0.16 output-2.mkv
> # for subordinate-2
> k4arecorder.exe --device 2 --external-

Hi @iammarvelous can you open a new issue please?

**Comment by iammarvelous** [comment]
@wes-b Done. See ##862
