### ISSUE TITLE
high cpu utilization.

### ISSUE THREAD

**Issue by barakooda** [microsoft/Azure-Kinect-Sensor-SDK#517]
cpu : intel 7700HQ 
gpu : gtx 1080 mobile

60% + cpu utilization ...
10-30% + gpu utilization...

Maybe its just Azure Kinect Viewer issue.

**Comment by cdedmonds** [comment]
@barakooda there will be higher CPU utilization in the viewer than when using the SDK. Also note that at higher RGB resolutions more CPU is used to convert from the camera's native pixel format to BGRA so use the resolution that best matches your needs.

**Comment by cdedmonds** [comment]
@barakooda I determined that the issue on my machine was unrelated. Can you provide some more details on SDK version, operating system version, and camera mode?

**Comment by barakooda** [comment]
sdk version : 1.1
screenshots:
https://ufile.io/e2kj2ks5

**Comment by bibigone** [comment]
Can it be related to MJPEG -> BGRA decoding? I found that this decoding in Sensor SDK is very slow and consumes a lot of CPU.

**Comment by Gnimuc** [comment]
> 10-30% + gpu utilization...

This is very likely due to IMGUI on which the Azure Kinect Viewer is based. Merely running [the IMGUI demo code](https://github.com/ocornut/imgui#demo-binaries) will cost ~20% GPU utilization, even if no UI widget is being drawed on the screen.  But I don't think this is a big deal though, unused resources are wasted resources :).

**Comment by wes-b** [comment]
Thanks, this usage is by design. We do expect an added CPU and GPU load with using the K4aViewer tool.
