### ISSUE TITLE
hello, how to read and record the infrared video or image like depth (16 bit single channel), infrared (16 bit single channel), rgb (8 bit 3 channels)

### ISSUE THREAD

**Issue by zcl912** [microsoft/Azure-Kinect-Sensor-SDK#638]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: 
 - SDK Version:  
 - Firmware version:  

**Additional context**

**Comment by rabbitdaxi** [comment]
@zcl912 is this page [page](https://docs.microsoft.com/en-us/azure/Kinect-dk/record-playback-api) in the documentation website can help resolve your issue?

**Comment by cdedmonds** [comment]
@zcl912 please let us know whether that page helps. We will need more details on what you are trying to accomplish to be able to diagnose this correctly.

**Comment by zcl912** [comment]
> @zcl912 please let us know whether that page helps. We will need more details on what you are trying to accomplish to be able to diagnose this correctly.

sorry for late reply, the prob, the problem is not solved

**Comment by rabbitdaxi** [comment]
@zcl912 if the SDK record/playback API did not solve your problem, can your provide more details of what is your problem exactly is?

**Comment by wes-b** [comment]
Hi @zcl912 if you are still having an issue please use our issue template to provide us with more detailed information about the problem. Right now we don't have enough information to help.

>Describe the bug
To Reproduce
Expected behavior
Logs
Screenshots
Desktop (please complete the following information):
OS with Version:
SDK Version:
Firmware version:
Additional context
