### ISSUE TITLE
Azure Kinect driver issue

### ISSUE THREAD

**Issue by FuntestechGithub** [microsoft/Azure-Kinect-Sensor-SDK#682]
Hi there,

I checked others' screenshots on Azure Kinect in device manager and found mine installed in different way.  Screenshot below:
![image](https://user-images.githubusercontent.com/53668234/63735180-2e2ffa80-c83c-11e9-955d-c8b43e40770e.png)
![image](https://user-images.githubusercontent.com/53668234/63735188-36883580-c83c-11e9-8adc-7311fbb1109d.png)

As result, built k4areviewer can enable color camera but not depth camera. (prebuilt viewer coming with SDK doesn't have such issue) I received following log.
![image](https://user-images.githubusercontent.com/53668234/63735277-7fd88500-c83c-11e9-8aea-164fbca179ed.png)

As upgrading firmware is suggested in the log, I tried to update the firmware (the one available in SDK 1.2.0), then got following errors.
![image](https://user-images.githubusercontent.com/53668234/63735472-2c1a6b80-c83d-11e9-8730-8ad61e2c62bc.png)

I've tried to uninstall driver and install it with plugging camera into different USB 3.0 ports. No luck so far. Thank you in advanced for your help

**Comment by wes-b** [comment]
Try installing the MSI, closing everything that might be using the color or depth camera (reboot even). Then run the k4aViewer instance that comes with the MSI.

Your first error is because the depth engine is missing, so you are not installed right. The 2nd you may have figured out or it may be because something else is using it. The last one I am not sure about.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wes-b** [comment]
Ok let's focus on getting k4aViewer running. There should only be one instance installed, make sure all other versions are uninstalled. Then run the viewer for the 1.2.0 you have installed. It should just work because the depth engine and the viewer are installed side by side. If it is not working, find the install path and cd into that folder and run from a command prompt after confirming they are side by side.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
