### ISSUE TITLE
k4a_calibration_3d_to_2d fails

### ISSUE THREAD

**Issue by thundercarrot** [microsoft/Azure-Kinect-Sensor-SDK#691]
Moving my application from SDK 1.0 to 1.2 I find that k4a_calibraiton_3d_to_2d now fails with:

[2019-08-28 08:01:32.159] [error] [t=31244] [K4A] D:\a\1\s\sdk\src\transformation\transformation.c (178): transformation_possible(calibration, target_camera) returned failure in transformation_3d_to_2d
[2019-08-28 08:01:32.159] [error] [t=31244] [K4A] D:\a\1\s\sdk\src\sdk\k4a.c (888): transformation_3d_to_2d( calibration, source_point3d->v, source_camera, target_camera, target_point2d->v, valid) returned failure in k4a_calibration_3d_to_2d

To reproduce, run the opencv_compatibility example (no need to compile with OpenCV).

**Comment by rabbitdaxi** [comment]
@thundercarrot , thank you for reporting. However, I have the latest develop branch with the 1.2.0 SDK installed, I did try to run opencv_example.exe that you mentioned, and I cannot repro this issue. Also, there is not functional change between 1.0 to 1.2 around the function you are referring to. 

Can you try to run opencv_example.exe one more time to repro and paste the full call stack? Or can you share your code that can repro this issue that we can figure out what is happening?

By the way, if you look at the code, the transformation_possible source code, there is only a few reasons that can return failure, one is because the input camera type not expected (source or target)

**Comment by thundercarrot** [comment]
It might be relevant that I'm using Visual Studio 2019. I took exactly the main.cpp and project file from the opencv_compatibility directory and retargeted the project to 2019 (I do not have 2017 installed). Would you be able to try to repro on 2019?

Also, it appears that calibration.depth_mode and color_mode have uninitialized values (in the Debug build 0xcccccccc) after getting the calibration structure from the sdk.

**Comment by rabbitdaxi** [comment]
@thundercarrot we cannot repro this even with VS 2019. And we see the depth_mode and color_resolution being set with the opencv_compatibility. Have you tried to just [build with terminal](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/building.md) with ninja and run opencv_example.exe and see whether you still can repro?

**Comment by rabbitdaxi** [comment]
@thundercarrot confirmed build with terminal is working.

**Comment by thundercarrot** [comment]
The issue was that my executable was finding an older version of k4a.dll before the newer one. I think I was incorrectly assuming that the .msi installer was taking care of the path variable.
