### ISSUE TITLE
mkv files can't be openened in the k4aviewer

### ISSUE THREAD

**Issue by Sara1702** [microsoft/Azure-Kinect-Sensor-SDK#755]
**Describe the bug**
Recordings produced by k4arecorder won't open in the k4aviewer 

**To Reproduce**
1.  Record through command prompt and save recording in an mkv file
PS C:\Program Files\Azure Kinect SDK v1.2.0\tools> .\k4arecorder.exe test.mkv
2. Open k4aviewer
3. Click Open Recording
4. Select test.mkv in order to open 
5. See error: Error! Failed to open recording!

**Expected behavior**
Displaying recording

**Logs**

**Desktop (please complete the following information):**
 - OS with Version: Windows 10 Enterprise
 - SDK Version:  v.1.2.0
 - Firmware version:  
RGB Camera: 1.6.102
Depth Camera: 1.6.75
Audio: 1.6.14
Build Config: Release
Signature type: Microsoft

**Comment by wes-b** [comment]
By default the recorder captures infinitely. Based on the command line you shared, k4arecorder would write to test.mkv until you hit CTRL-C or ran out of disk. 

I think v4aviewer was unable to open test.mkv because it is still being written to by k4arecorder.exe.

Try `k4arecorder.exe -l 15 test.mkv`
