### ISSUE TITLE
Color to depth to point cloud accuracy flaws

### ISSUE THREAD

**Issue by ichlubna** [microsoft/Azure-Kinect-Sensor-SDK#761]
Hello!
When generating the XY table and applying it in the point cloud I am getting [this inaccuracy](https://imgur.com/a/IvlAJpj). Like parts of the foreground are visible in the background nearby the depth sensor shadow. It happens even in the official k4awiever example. Is there any way to fix this? Maybe it's caused by the color to depth conversion or XY table values?

Built the latest SDK on Arch Linux, using Depth Engine from NuGet package.

**Comment by rabbitdaxi** [comment]
@ichlubna thanks for the feedback. Yes, point cloud rendering could be slow if you have higher resolution of the final depth image. e.g. if you do depth to color, given color has higher resolution, it means you have more 3d points to render. This is a quite common fact though (you can accelerate the point cloud generate by having it on GPU and pay the memory of storing the xytable, and also assuming the rendering engine is fast enough to render lots of 3d points). The depth to color transform should be fast enough because of it is on GPU.
