### ISSUE TITLE
Specific memory allocators per device and frame type

### ISSUE THREAD

**Issue by tim-depthkit** [microsoft/Azure-Kinect-Sensor-SDK#891]
I'd like to reduce the CPU overhead required for copying the frame data coming out of the Azure Kinect SDK. I've seen that there is support for a user defined memory allocator callback, but in order to make use of this feature, I would need some way of knowing at allocation time if the memory being requested is going to be used for a color frame, depth frame, etc, and how many frames are being allocated at the time. If this were available, I would be able to remove the expensive memory copies that I am currently using to shuttle data out of the SDK and into the rest of my application's processing pipeline.

My system's pipeline reuses frame data internally when it is no longer needed, but it is currently not possible to integrate into the memory allocation/deallocation part of the Azure Kinect SDK, because there is no way to know what the memory being allocated will be used for. If I could know at allocation time that the requested memory would be used for a single color frame, for example, I could request that memory from our processing pipeline and get an already allocated buffer that is the right size, and avoid the need to copy any memory.

Additionally, in order to make the best use of an allocator function, we need to know which device is requesting the allocation, so we can use memory that is already assigned to the processing pipeline for that device.

I propose either separate device specific allocator & deallocator functions for each frame type (color/depth/IR/etc)
OR
Alternatively, adding in an enum parameter to the existing single allocator callback that specifies the type of data that will be allocated, and how many frames it shall represent, and the device handle that is requesting it.

**Comment by Brent-A** [comment]
Hi Tim, 

This is an interesting scenario, but I think it would be a bit tricky to implement. The allocator callback needs to do things like pad the allocation for alignment and to attach book keeping metadata, so there isn't a direct correspondence with the allocation and the location that the image data will be stored. The best you can do is examine an image buffer's pointer and validate that it falls in the range of a pre-allocated buffer you provided through the allocator hook.

Maybe an option to prevent the SDK from creating its own k4a_image_t objects paired with a function like k4a_device_add_image_to_pool would do what you want. This isn't entirely trivial to implement because there are some internal considerations around managing the depth and IR buffers as a single block of memory, as well as interoperating with the media foundation stack.

I don't think the Microsoft team will do the work to add this soon, but if you find a way to get what you need by hacking the source we'd be interested in helping get that turned in to an API.
